CREATE TABLE tokens (
  token VARCHAR(60) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL UNIQUE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (token),
  FOREIGN KEY (user_id) REFERENCES users(id)
); 